### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by junhong0618** [Rexpert/TNG_Statement_in_CSV#1] opened 2023-11-24 05:47 UTC
Hi Sir. I am new to github. I have installed camelot-py and pandas in CMD. My python's version is 3.11.4. After copying down you code and pasting into VSC, I changed your **r'.\data\tng_ewallet_transactions.pdf'** to my downloaded statement path **r'C:\Users\P1357685\Downloads\tng_ewallet_transactions.pdf'** and **r'.\output\tng_ewallet_transactions.csv'** to **r'C:\Users\P1357685\Downloads\tng_ewallet_transactions.csv'**. After I ran the code, import error occurred as below:

Traceback (most recent call last):
  File "c:\Users\P1357685\Downloads\CSV TNG.py", line 3, in <module>
    import camelot
  File "C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\camelot\__init__.py", line 6, in <module>
    from .io import read_pdf
  File "C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\camelot\io.py", line 5, in <module>
    from .handlers import PDFHandler
  File "C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\camelot\handlers.py", line 8, in <module>
    from .core import TableList
ImportError: cannot import name 'TableList' from 'camelot.core' (C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\camelot\core\__init__.py)

I appreciate your advise as I am new to this field. Looking forward to your guidances.

**Comment by Rexpert** [comment] 2023-11-24 06:12
Hi @junhong0618 Thanks for reaching out,

could you please verify your `camelot-py` version == 0.10.1:
 ```
> pip list
```

**Comment by junhong0618** [comment] 2023-11-24 06:16
> Hi @junhong0618 Thanks for reaching out,
> 
> could you please verify your `camelot-py` version == 0.10.1:
> 
> ```
> > pip list
> ```

**Comment by junhong0618** [comment] 2023-11-24 06:19
> Hi @junhong0618 Thanks for reaching out,
> 
> could you please verify your `camelot-py` version == 0.10.1:
> 
> ```
> > pip list
> ```

Accidentally closed the comment. Thanks for your prompt reply. 
My camelot-py version is 0.11.0
Must it be exactly 0.10.1?

**Comment by Rexpert** [comment] 2023-11-24 07:04
> Accidentally closed the comment. Thanks for your prompt reply. My camelot-py version is 0.11.0 Must it be exactly 0.10.1?

@junhong0618 My python version is 3.10.9, but the camelot-py highest version i can install is 0.10.1, I'll try to install `python==3.11.4` & `camelot-py==0.11.0` in another workspace to simulate your situation...

At the meantime, can you please try the following solution, ie: re-install camelot-py
> you might want to reinstall it. Camelot and camelot-py are two different packages but they have the same import name.
> ```
> pip uninstall camelot
> pip uninstall camelot-py
> pip install camelot-py[cv]
> ```

> Source: [ImportError: cannot import name 'TableList' from 'camelot.core'](https://stackoverflow.com/questions/61913882/importerror-cannot-import-name-tablelist-from-camelot-core)

**Comment by junhong0618** [comment] 2023-11-24 07:34
> > Accidentally closed the comment. Thanks for your prompt reply. My camelot-py version is 0.11.0 Must it be exactly 0.10.1?
> 
> EDIT: I have no said import issue with the setup `python==3.11.4` & `camelot-py==0.11.0`
> 
> @junhong0618 My python version is 3.10.9, but the camelot-py highest version i can install is 0.10.1, I'll try to install `python==3.11.4` & `camelot-py==0.11.0` in another workspace to simulate your situation...
> 
> At the meantime, can you please try the following solution, ie: re-install camelot-py
> 
> > you might want to reinstall it. Camelot and camelot-py are two different packages but they have the same import name.
> > ```
> > pip uninstall camelot
> > pip uninstall camelot-py
> > pip install camelot-py[cv]
> > ```
> 
> > Source: [ImportError: cannot import name 'TableList' from 'camelot.core'](https://stackoverflow.com/questions/61913882/importerror-cannot-import-name-tablelist-from-camelot-core)

You are right. I installed both camelot and camelot-py modules. After I did the solutions as you mentioned, new message occured about PyPDF2 module. Do we need this module in this code?

**Comment by Rexpert** [comment] 2023-11-24 07:40
> You are right. I installed both camelot and camelot-py modules. After I did the solutions as you mentioned, new message occured about PyPDF2 module. Do we need this module in this code?

I don't use `PyPDF2` in this repository, I think it's `camelot-py`'s dependency. Do you have the specific message / error for that?

**Comment by junhong0618** [comment] 2023-11-24 07:49
> 
> I don't use `PyPDF2` in this repository, I think it's `camelot-py`'s dependency. Do you have the specific message / error for that?

Pasted the whole message for you and bolded the PyPDF2 occurence. I'm confused why does it suddenly involve PyPDF2 in the run. 

Traceback (most recent call last):
  File "c:\Users\P1357685\Downloads\CSV TNG.py", line 6, in <module>
    table = camelot.read_pdf(r'C:\Users\P1357685\Downloads\data\tng_ewallet_transactions.pdf', pages='all', flavor='stream',    
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\camelot\io.py", line 111, in read_pdf       
    p = PDFHandler(filepath, pages=pages, password=password)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\camelot\handlers.py", line 50, in __init__  
    self.pages = self._get_pages(self.filepath, pages)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\camelot\handlers.py", line 74, in _get_pages
    infile = PdfFileReader(instream, strict=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  **File "C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyPDF2\_reader.py", line 1974, in __init__
    deprecation_with_replacement("PdfFileReader", "PdfReader", "3.0.0")
  File "C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyPDF2\_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File "C:\Users\P1357685\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyPDF2\_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
PyPDF2.errors.DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.**

**Comment by Rexpert** [comment] 2023-11-24 08:04
This is caused by `camelot-py` uses deprecated `PyPDF2` function but not updating it in the latest version.
For a temporary fix, I think you need to install a lower version of `PyPDF2` (for eg: mine has a 2.11.1)
```
> pip install pypdf2==2.11.1
```

**Comment by Rexpert** [comment] 2023-11-24 08:15
Anyway, I think this import issue has been successfully dealt with, since you can import camelot without error... And so I think I can close this issue.
For organize sake, it would be better if you open another issue regarding different subject. 
Thank you for using my repo, please let me know if any trouble, I am happy to assist.

**Closed by Rexpert** 2023-11-24 08:15 UTC
